#!/bin/bash

echo "Kuu number:"
read kuu

if (( kuu == 12 || kuu == 1 || kuu == 2 ))
then
    echo "Talv"
elif (( kuu == 3 || kuu == 4 || kuu == 5 ))
then
    echo "Kevad"
elif (( kuu == 6 || kuu == 7 || kuu == 8 ))
then 
    echo "Suvi"
elif (( kuu == 9 || kuu == 10 || kuu == 11))
then
    echo "Sugis"
else
    echo "Tauni sundroom"
fi
