#!/bin/bash

aeg=$(date +%H)
kasutaja=$(whoami)

if (( aeg >= 6 && aeg < 12 ))
then
    echo "Tere hommiku, $kasutaja!"
elif (( aeg >= 12 && aeg < 18 ))
then
    echo "Tere paevast, $kasutaja!"
elif (( aeg >= 18 && aeg < 22 ))
then
    echo "Tere ohtut, $kasutaja!"
else 
    echo "Head ood, $kasutaja!"
fi
